#!/usr/bin/env node

import vorpal from "vorpal"

const client = vorpal()

client
  .command("generate complete import")
  .action(function generateCompleteImport (parameters: object, callback: Function) {
    this.log("bar")

    callback()
  })
